version: "3.7"
services:
    app_laravel:
        build:
            context: .
            dockerfile: Dockerfile
        # image is the name of the image we want to build
        image: "business_directory_app"
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        # depends_on will make sure that the db_mysql container is running before the app_laravel container starts
        depends_on:
            - db_mysql

    db_mysql:
        build:
            context: .
            dockerfile: Dockerfile.db # Use the new Dockerfile for MySQL
        # restart: always will make sure that the container restarts if it crashes
        restart: always
        ports:
            - "3309:3306"
        environment:
            MYSQL_DATABASE: db_business_directory
            MYSQL_ROOT_PASSWORD: business_directory
            MYSQL_USER: business_directory
            MYSQL_PASSWORD: business_directory
        volumes:
        # Mount the dump file to the docker-entrypoint-initdb.d folder
        # Change the path to the dump file to match your project
        # In this case it's in the root of the project
            - ./business_directory.sql:/docker-entrypoint-initdb.d/business_directory.sql
